services:
  myfinances.api:
    image: myfinances.api
    build:
      context: .
      dockerfile: MyFinances.Api/Dockerfile

  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      MSSQL_SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

volumes:
  sql-data:
